name: Build & Release on Tag
on:
  push:
    tags:
      - '*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: stable
      - name: Build release
        run: cargo build --release
      - name: Strip binary
        run: strip target/release/npm-audit-to-report
      - name: Upload release binary as artifact
        uses: actions/upload-artifact@v6
        with:
          name: npm-audit-to-report
          path: target/release/npm-audit-to-report
      - name: Create GitHub Release & Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/npm-audit-to-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
